# r objects

## list

In [3]:
#Creating a list 
list_1 <- list("Red","Green", c(21,32,11), TRUE, 51.23, 119.1)
print(list_1)

[[1]]
[1] "Red"

[[2]]
[1] "Green"

[[3]]
[1] 21 32 11

[[4]]
[1] TRUE

[[5]]
[1] 51.23

[[6]]
[1] 119.1



In [4]:
#NAMING LIST ELEMENTS
list_2 <- list(c("Jan","Feb","Mar"), matrix(c(3,9,5,1,-2,8)),nrow = 2,list("green",12.3))
#Gives names to elements 
names(list_2) <- c("1st Quarter", "A_Matrix","A Inner list")
#print list
print(list_2)

$`1st Quarter`
[1] "Jan" "Feb" "Mar"

$A_Matrix
     [,1]
[1,]    3
[2,]    9
[3,]    5
[4,]    1
[5,]   -2
[6,]    8

$`A Inner list`
[1] 2

$<NA>
$<NA>[[1]]
[1] "green"

$<NA>[[2]]
[1] 12.3




In [5]:
#ACCESSING LIST ELLEMENTS
#Accessing first element of the list
print(list_2[1])
#Accessing third element of the list which is also a list
print(list_2[3])
#Accessing list element using name of element
print(list_2$A_Matrix)

$`1st Quarter`
[1] "Jan" "Feb" "Mar"

$`A Inner list`
[1] 2

     [,1]
[1,]    3
[2,]    9
[3,]    5
[4,]    1
[5,]   -2
[6,]    8


In [6]:
# Manipulating List elements
#ADD element at end of list
list_2[4] <- "New Element"
print(list_2[4])

#Remove the last element
list_2[4] <- NULL

#print the 4th element
print(list_2[4])

#Update the 3rd Element
list_2[3] <- "Updated Element"
print(list_2[3])

$<NA>
[1] "New Element"

$<NA>
NULL

$`A Inner list`
[1] "Updated Element"



In [7]:
#MERGING LIST

list1 <- list(1,2,3)
list2 <- list("Sun","Mon","Tue")

#merging both lists
merged.list <- c(list1,list2)
#print merged list
print(merged.list)

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] "Sun"

[[5]]
[1] "Mon"

[[6]]
[1] "Tue"



In [8]:
#CONVERT LIST TO VECTOR

#Create a list
list1 <- list(1:5)
print(list1)

list2 <- list(10:14)
print(list2)

#convert List to vectors
v1 <- unlist(list1)
v2 <- unlist(list2)
print(v1)
print(v2)

#now Add the vectors
result <- v1+v2
print(result)

[[1]]
[1] 1 2 3 4 5

[[1]]
[1] 10 11 12 13 14

[1] 1 2 3 4 5
[1] 10 11 12 13 14
[1] 11 13 15 17 19


In [9]:
#MATRIX
#Elements arranged by  row
M <- matrix(c(3:14),nrow=4,byrow=TRUE)
print(M)
#Element arranged by column
N <- matrix(c(3:14),nrow=4,byrow=FALSE)
print(N)
#Define the column and row names
rownames=c("row1","row2","row3","row4")
colnames=c("col1","col2","col3")

p <- matrix(c(3:14),nrow=4,byrow=TRUE,dimnames=list(rownames,colnames))
print(p)

     [,1] [,2] [,3]
[1,]    3    4    5
[2,]    6    7    8
[3,]    9   10   11
[4,]   12   13   14
     [,1] [,2] [,3]
[1,]    3    7   11
[2,]    4    8   12
[3,]    5    9   13
[4,]    6   10   14
     col1 col2 col3
row1    3    4    5
row2    6    7    8
row3    9   10   11
row4   12   13   14


In [11]:
## Accessing elements of matrix
rownames=c("row1","row2","row3","row4")
colnames=c("col1","col2","col3")
p <- matrix(c(3:14),nrow=4,byrow=TRUE,dimnames=list(rownames,colnames))
#Accessing elements at 3rd column and 1st row
print(p[1,3])
#Accessing elements at 2rd column and 4st row
print(p[4,2])
#Accessing only 2nd row
print(p[2,])

[1] 5
[1] 13
col1 col2 col3 
   6    7    8 


In [12]:
#MATRIX ADDITION AND SUBTRACTION
matrix1 <- matrix(c(3,9,-1,4,2,6),nrow=2)
print(matrix1)
matrix2 <- matrix(c(5,2,0,9,3,4),nrow=2)
print(matrix2)
#ADD MATRIX
result <- matrix1 + matrix2
cat("Result of addition","\n")
print(result)
#subtraction
result <- matrix1 - matrix2
cat("Result of subtraction","\n")
print(result)

     [,1] [,2] [,3]
[1,]    3   -1    2
[2,]    9    4    6
     [,1] [,2] [,3]
[1,]    5    0    3
[2,]    2    9    4
Result of addition 
     [,1] [,2] [,3]
[1,]    8   -1    5
[2,]   11   13   10
Result of subtraction 
     [,1] [,2] [,3]
[1,]   -2   -1   -1
[2,]    7   -5    2


In [13]:
#MATRIX ADDITION AND SUBTRACTION
matrix1 <- matrix(c(3,9,-1,4,2,6),nrow=2)
print(matrix1)
matrix2 <- matrix(c(5,2,0,9,3,4),nrow=2)
print(matrix2)
#ADD MATRIX
result <- matrix1 * matrix2
cat("Result of multiplication","\n")
print(result)
#subtraction
result <- matrix1 / matrix2
cat("Result of division","\n")
print(result)

     [,1] [,2] [,3]
[1,]    3   -1    2
[2,]    9    4    6
     [,1] [,2] [,3]
[1,]    5    0    3
[2,]    2    9    4
Result of multiplication 
     [,1] [,2] [,3]
[1,]   15    0    6
[2,]   18   36   24
Result of division 
     [,1]      [,2]      [,3]
[1,]  0.6      -Inf 0.6666667
[2,]  4.5 0.4444444 1.5000000


In [16]:
#Arrays
#creae 2 vectors
vector1 <- c(5,9,3)
vector2 <- c(10:16)
#takes vectors as input to array
result <- array(c(vector1,vector2),dim = c(3,3,2))
print(result)

, , 1

     [,1] [,2] [,3]
[1,]    5   10   13
[2,]    9   11   14
[3,]    3   12   15

, , 2

     [,1] [,2] [,3]
[1,]   16    3   12
[2,]    5   10   13
[3,]    9   11   14



In [18]:
#Naming column and rows
vector1 <- c(5,9,3)
vector2 <- c(10:16)
column.names <- c("COL1","COL2","COL3")
row.names <- c("ROW1","ROW2","ROW3")
matrix.names <- c("Matrix1","Matrix2")
#take these vectors as input to array
result <- array(c(vector1,vector2),dim = c(3,3,2),dimnames=list(row.names,column.names,
                                                                matrix.names))
print(result)

, , Matrix1

     COL1 COL2 COL3
ROW1    5   10   13
ROW2    9   11   14
ROW3    3   12   15

, , Matrix2

     COL1 COL2 COL3
ROW1   16    3   12
ROW2    5   10   13
ROW3    9   11   14



In [19]:
#Accessing Array elements
#print third row of second matrix of array
print(result[3,,2])
#print element in 1st row and 3rd column of 1st matrix
print(result[1,3,1])
#print 2nd matrix
print(result[,,2])

COL1 COL2 COL3 
   9   11   14 
[1] 13
     COL1 COL2 COL3
ROW1   16    3   12
ROW2    5   10   13
ROW3    9   11   14


In [20]:
#Manipulating Array elements
vector1 <- c(5,9,3)
vector2 <- c(10:16)
#take these vector as input to array
array1 <- array(c(vector1,vector2),dim = c(3,3,2))

vector3 <- c(9,1,0)
vector4 <- c(6,0,11,3,14,1,2,6,9)
#take these vector as input to array
array2 <- array(c(vector3,vector4),dim = c(3,3,2))
#create matrix from these array
matrix1 <- array1[,,2]
matrix2 <- array2[,,2]
#add the arrays
result <- matrix1+matrix2
print(result)

     [,1] [,2] [,3]
[1,]   18   12   18
[2,]   11   11   13
[3,]   18   11   25


In [21]:
#using .apply
vector1 <- c(5,9,3)
vector2 <- c(10:16)
#take these vector as input to array
array1 <- array(c(vector1,vector2),dim = c(3,3,2))
#use apply to calculate sum of rows across all matrices
result <- apply(array1,c(1), sum)
print(result)

[1] 59 62 64


In [22]:
#FACTORS

data <- c("EAST","WEST","EAST","NORTH","EAST","WEST","EAST","SOUTH","WEST","WEST")

print(data)
print(is.factor(data))

#APPLY FACTOR FUNCTION
factor_data <- factor(data)

print(factor_data)
print(is.factor(factor_data))

 [1] "EAST"  "WEST"  "EAST"  "NORTH" "EAST"  "WEST"  "EAST"  "SOUTH" "WEST" 
[10] "WEST" 
[1] FALSE
 [1] EAST  WEST  EAST  NORTH EAST  WEST  EAST  SOUTH WEST  WEST 
Levels: EAST NORTH SOUTH WEST
[1] TRUE


In [23]:
#FACTOR IN DATA FRAME

height <- c(132,151,162,138,122,145,122)
weight <- c(48,49,66,53,67,52,40)
gender <- c("male","male","female","female","male","female","male")
#Create the data frame
input_data <- data.frame(height,weight,gender)
print(input_data)

#Test if gender column is a factor
print(is.factor(input_data$gender))
#print gender column so see the levels
print(input_data$gender)

  height weight gender
1    132     48   male
2    151     49   male
3    162     66 female
4    138     53 female
5    122     67   male
6    145     52 female
7    122     40   male
[1] TRUE
[1] male   male   female female male   female male  
Levels: female male


In [25]:
#change order of levels
data <- c("EAST","WEST","EAST","NORTH","EAST","WEST","EAST","SOUTH","WEST","WEST")
#create factor
factor_data <- factor(data)
print(factor_data)
#apply factor function with required order of level
new_order_data <- factor(factor_data,levels = c("EAST","WEST","NORTH"))
print(new_order_data)

 [1] EAST  WEST  EAST  NORTH EAST  WEST  EAST  SOUTH WEST  WEST 
Levels: EAST NORTH SOUTH WEST
 [1] EAST  WEST  EAST  NORTH EAST  WEST  EAST  <NA>  WEST  WEST 
Levels: EAST WEST NORTH


In [26]:
#generating factor levels
v <- gl(3,4,labels=c("Tampa", "Seattle", "Boston"))
print(v)

 [1] Tampa   Tampa   Tampa   Tampa   Seattle Seattle Seattle Seattle Boston 
[10] Boston  Boston  Boston 
Levels: Tampa Seattle Boston


In [29]:
# DATAFRAMES
#create dataframe

emp.data <- data.frame(
    emp_id = c(1:5),
    emp_name = c("Rick","DAN","ROCK","BOB","ROSS"),
    salary = c(112.3,222.3,423.5,567.65,876),
    start_date = as.Date(c("2012-01-01","2013-09-23","2014-11-15","2014-05-11",
                           "2015-03-27")),
    stringsAsFactors = FALSE
)
print(emp.data)

  emp_id emp_name salary start_date
1      1     Rick 112.30 2012-01-01
2      2      DAN 222.30 2013-09-23
3      3     ROCK 423.50 2014-11-15
4      4      BOB 567.65 2014-05-11
5      5     ROSS 876.00 2015-03-27


In [31]:
#GET STRUCTURE OF DATAFRAME

str(emp.data)

'data.frame':	5 obs. of  4 variables:
 $ emp_id    : int  1 2 3 4 5
 $ emp_name  : chr  "Rick" "DAN" "ROCK" "BOB" ...
 $ salary    : num  112 222 424 568 876
 $ start_date: Date, format: "2012-01-01" "2013-09-23" ...


In [32]:
#Get statistical summary of dataframe
print(summary(emp.data))

     emp_id    emp_name             salary        start_date        
 Min.   :1   Length:5           Min.   :112.3   Min.   :2012-01-01  
 1st Qu.:2   Class :character   1st Qu.:222.3   1st Qu.:2013-09-23  
 Median :3   Mode  :character   Median :423.5   Median :2014-05-11  
 Mean   :3                      Mean   :440.4   Mean   :2014-01-14  
 3rd Qu.:4                      3rd Qu.:567.6   3rd Qu.:2014-11-15  
 Max.   :5                      Max.   :876.0   Max.   :2015-03-27  


In [33]:
# Extract column Data from dataframe

emp.data <- data.frame(
    emp_id = c(1:5),
    emp_name = c("Rick","DAN","ROCK","BOB","ROSS"),
    salary = c(112.3,222.3,423.5,567.65,876),
    start_date = as.Date(c("2012-01-01","2013-09-23","2014-11-15","2014-05-11",
                           "2015-03-27")),
    stringsAsFactors = FALSE
)

#Extract specific column
result <- data.frame(emp.data$emp_name,emp.data$salary)
print(result)

  emp.data.emp_name emp.data.salary
1              Rick          112.30
2               DAN          222.30
3              ROCK          423.50
4               BOB          567.65
5              ROSS          876.00


In [34]:
#Extract rows from dataframe
#Extract first 2 rows 
result <- emp.data[1:2,]
print(result)

  emp_id emp_name salary start_date
1      1     Rick  112.3 2012-01-01
2      2      DAN  222.3 2013-09-23


In [35]:
#Extract rows and columns from dataframe via indexing
#Extract 3rd and 5th row wit 2nd and 4th colum
result <- emp.data[c(3,5),c(2,4)]
print(result)

  emp_name start_date
3     ROCK 2014-11-15
5     ROSS 2015-03-27


In [36]:
#Expanding Dataframe by adding Column
emp.data <- data.frame(
    emp_id = c(1:5),
    emp_name = c("Rick","DAN","ROCK","BOB","ROSS"),
    salary = c(112.3,222.3,423.5,567.65,876),
    start_date = as.Date(c("2012-01-01","2013-09-23","2014-11-15","2014-05-11",
                           "2015-03-27")),
    stringsAsFactors = FALSE
)
# ADD the Dept column
emp.data$dept<- c("IT","OPERATIONS","IT","HR","FINANCE")
print(emp.data)

  emp_id emp_name salary start_date       dept
1      1     Rick 112.30 2012-01-01         IT
2      2      DAN 222.30 2013-09-23 OPERATIONS
3      3     ROCK 423.50 2014-11-15         IT
4      4      BOB 567.65 2014-05-11         HR
5      5     ROSS 876.00 2015-03-27    FINANCE


In [40]:
#ADDING ROWS IN A DATAFRAME
emp.data <- data.frame(
    emp_id = c(1:5),
    emp_name = c("Rick","DAN","ROCK","BOB","ROSS"),
    salary = c(112.3,222.3,423.5,567.65,876),
    start_date = as.Date(c("2012-01-01","2013-09-23","2014-11-15","2014-05-11",
                           "2015-03-27")),
    dept= c("IT","OPERATIONS","IT","HR","FINANCE"),
    stringsAsFactors = FALSE
)
#create another dataframe
emp.newdata <- data.frame(
    emp_id = c(6:8),
    emp_name = c("Rasmo","pranab","Tushar"),
    salary = c(112.3,222.3,423.5),
    start_date = as.Date(c("2013-05-21","2013-07-30","2014-06-17")),
    dept = c("IT","Operations","Finance"),
    stringsAsFactors = FALSE
)
#BIND THE TWO DATAFRAMES USING RBIND()
emp.finaldata <- rbind(emp.data,emp.newdata)
print(emp.finaldata)

  emp_id emp_name salary start_date       dept
1      1     Rick 112.30 2012-01-01         IT
2      2      DAN 222.30 2013-09-23 OPERATIONS
3      3     ROCK 423.50 2014-11-15         IT
4      4      BOB 567.65 2014-05-11         HR
5      5     ROSS 876.00 2015-03-27    FINANCE
6      6    Rasmo 112.30 2013-05-21         IT
7      7   pranab 222.30 2013-07-30 Operations
8      8   Tushar 423.50 2014-06-17    Finance


In [ ]:
#MEAN
x <- c(1:50)

results.mean <- mean(x)
print(result.mean)